version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    command: npm start
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    hostname: my-rabbit
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia/
    ports:
      - 5672:5672
      - 15672:15672
